### ISSUE TITLE
Support for 4-band Uint16 sources

### ISSUE THREAD

**Issue by mojodna** [hotosm/oam-dynamic-tiler#27]
E.g. s3://hotosm-oam/15APR27052125-S3DS_R02C6-054335918020_01_P001.TIF

```
Band 1 Block=7660x68 Type=UInt16, ColorInterp=Red
Band 2 Block=7660x68 Type=UInt16, ColorInterp=Green
Band 3 Block=7660x68 Type=UInt16, ColorInterp=Blue
Band 4 Block=7660x68 Type=UInt16, ColorInterp=Undefined
```

JPEG compression only works by default on 8-bit bands. It [can work in 12-bit](https://trac.osgeo.org/gdal/wiki/TIFF12BitJPEG) against 16-bit bands.

We should either enable 12-bit JPEG compression or use `DEFLATE` for such images.

@smit1678 @cgiovando thoughts?

(Did/should we specify this away for OIN by requiring **8-bit** RGB(A) sources?)

**Comment by smit1678** [comment]
> (Did/should we specify this away for OIN by requiring 8-bit RGB(A) sources?)

@mojodna Saw that you implemented a solution. 👍  I don't think we specify this much more than [just saying RGB geotiffs](https://github.com/openimagerynetwork/oin-register#imagery-format).
