### ISSUE TITLE
Vulnerability patch: upgrade nodejs to 6.11.1

### ISSUE THREAD

**Issue by tombh** [hotosm/oam-dynamic-tiler#44]
@mojodna do all pushes here trigger a rebuild of `quay.io/hotosm/oam-dynamic-tiler-tools
`? Or can you just manually trigger a rebuild for us? We need the latest nodejs in production oam-uploader-api to patch a significant vulnerability. I assume the [line 22 in the Dockerfile here](https://github.com/hotosm/oam-dynamic-tiler/blob/master/Dockerfile#L22) will automatically fetch the latest nodejs?

**Comment by mojodna** [comment]
Correct.

It's building now: https://quay.io/repository/hotosm/oam-dynamic-tiler-tools/build/46035862-ea02-495b-b3e0-0fe2f572112d

**Comment by tombh** [comment]
Great, thanks.
